"""remove_signal_type_and_source_from_alerts

Revision ID: 562fc942c1d8
Revises: remove_user_is_active
Create Date: 2026-03-24 06:14:29.193534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '562fc942c1d8'
down_revision = 'remove_user_is_active'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'source')
    op.drop_column('alerts', 'signal_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('signal_type', postgresql.ENUM('MANUAL', 'AUTO', name='signaltype'), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
